export { default as Home } from "./Home";
export { default as Movie } from "./Movie";
export { default as TV } from "./TV";
export { default as MySpace } from "./MySpace";
export { default as Search } from "./Search";
export { default as HomeShowListByCat } from "./HomeShowListByCat";
export { default as MovieShowListByCat } from "./MovieShowListByCat";
export { default as TVShowListByCat } from "./TVShowListByCat";
export { default as HomeShowDetails } from "./HomeShowDetails";
